"""add analysis tables

Revision ID: 245b61468b11
Revises: c598cfa70b1d
Create Date: 2026-04-22 06:45:10.248365

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '245b61468b11'
down_revision: Union[str, Sequence[str], None] = 'c598cfa70b1d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analysis_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('import_id', sa.Integer(), nullable=True),
    sa.Column('started_by', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('tickets_limit', sa.Integer(), nullable=True),
    sa.Column('total_ticket_ids', sa.Integer(), nullable=True),
    sa.Column('fetched_tickets_count', sa.Integer(), nullable=True),
    sa.Column('analyzed_tickets_count', sa.Integer(), nullable=True),
    sa.Column('support_count', sa.Integer(), nullable=True),
    sa.Column('non_support_count', sa.Integer(), nullable=True),
    sa.Column('brand_tone_ai_suggested', sa.String(), nullable=True),
    sa.Column('summary_json', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['import_id'], ['import_files.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analysis_runs_id'), 'analysis_runs', ['id'], unique=False)
    op.create_table('ticket_classifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('analysis_run_id', sa.Integer(), nullable=True),
    sa.Column('ticket_id', sa.Integer(), nullable=True),
    sa.Column('ai_main_category', sa.String(), nullable=True),
    sa.Column('ai_subcategory', sa.String(), nullable=True),
    sa.Column('ai_confidence', sa.Float(), nullable=True),
    sa.Column('ai_reason', sa.String(), nullable=True),
    sa.Column('is_support_ticket', sa.Boolean(), nullable=True),
    sa.Column('suggested_new_main_category', sa.String(), nullable=True),
    sa.Column('suggested_new_subcategory', sa.String(), nullable=True),
    sa.Column('review_status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['analysis_run_id'], ['analysis_runs.id'], ),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ticket_classifications_id'), 'ticket_classifications', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ticket_classifications_id'), table_name='ticket_classifications')
    op.drop_table('ticket_classifications')
    op.drop_index(op.f('ix_analysis_runs_id'), table_name='analysis_runs')
    op.drop_table('analysis_runs')
    # ### end Alembic commands ###
