"""add import and ticket tables

Revision ID: c598cfa70b1d
Revises: d4c9a52e83ff
Create Date: 2026-04-22 06:17:45.176014

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c598cfa70b1d'
down_revision: Union[str, Sequence[str], None] = 'd4c9a52e83ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('import_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('uploaded_by', sa.Integer(), nullable=True),
    sa.Column('import_type', sa.String(), nullable=True),
    sa.Column('file_name', sa.String(), nullable=True),
    sa.Column('file_path', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_import_files_id'), 'import_files', ['id'], unique=False)
    op.create_table('import_ticket_ids',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('import_id', sa.Integer(), nullable=True),
    sa.Column('external_ticket_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['import_id'], ['import_files.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_import_ticket_ids_external_ticket_id'), 'import_ticket_ids', ['external_ticket_id'], unique=False)
    op.create_index(op.f('ix_import_ticket_ids_id'), 'import_ticket_ids', ['id'], unique=False)
    op.create_table('tickets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('import_id', sa.Integer(), nullable=True),
    sa.Column('external_ticket_id', sa.String(), nullable=True),
    sa.Column('subject', sa.String(), nullable=True),
    sa.Column('customer_message', sa.String(), nullable=True),
    sa.Column('agent_response', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('channel', sa.String(), nullable=True),
    sa.Column('created_at_source', sa.DateTime(), nullable=True),
    sa.Column('closed_at_source', sa.DateTime(), nullable=True),
    sa.Column('raw_ticket_json', sa.JSON(), nullable=True),
    sa.Column('is_valid_closed_ticket', sa.Boolean(), nullable=True),
    sa.Column('excluded_reason', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['import_id'], ['import_files.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tickets_external_ticket_id'), 'tickets', ['external_ticket_id'], unique=False)
    op.create_index(op.f('ix_tickets_id'), 'tickets', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tickets_id'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_external_ticket_id'), table_name='tickets')
    op.drop_table('tickets')
    op.drop_index(op.f('ix_import_ticket_ids_id'), table_name='import_ticket_ids')
    op.drop_index(op.f('ix_import_ticket_ids_external_ticket_id'), table_name='import_ticket_ids')
    op.drop_table('import_ticket_ids')
    op.drop_index(op.f('ix_import_files_id'), table_name='import_files')
    op.drop_table('import_files')
    # ### end Alembic commands ###
