"""add email to credentials

Revision ID: c5c282940950
Revises: 245b61468b11
Create Date: 2026-04-23 08:06:34.709334

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c5c282940950'
down_revision: Union[str, Sequence[str], None] = '245b61468b11'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client_platform_credentials', sa.Column('email', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('client_platform_credentials', 'email')
    # ### end Alembic commands ###
