"""add category and credentials tables

Revision ID: d4c9a52e83ff
Revises: f4185e8e4ecf
Create Date: 2026-04-22 06:14:29.692887

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd4c9a52e83ff'
down_revision: Union[str, Sequence[str], None] = 'f4185e8e4ecf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('platform_code', sa.String(), nullable=True),
    sa.Column('main_category', sa.String(), nullable=False),
    sa.Column('subcategory', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_category_templates_id'), 'category_templates', ['id'], unique=False)
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('main_category', sa.String(), nullable=False),
    sa.Column('subcategory', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_categories_id'), 'categories', ['id'], unique=False)
    op.create_table('client_platform_credentials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('credential_type', sa.String(), nullable=True),
    sa.Column('api_key_encrypted', sa.String(), nullable=False),
    sa.Column('api_base_url', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_client_platform_credentials_id'), 'client_platform_credentials', ['id'], unique=False)
    op.add_column('clients', sa.Column('brand_tone_mode', sa.String(), nullable=False))
    op.add_column('clients', sa.Column('brand_tone_ai_suggested', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clients', 'brand_tone_ai_suggested')
    op.drop_column('clients', 'brand_tone_mode')
    op.drop_index(op.f('ix_client_platform_credentials_id'), table_name='client_platform_credentials')
    op.drop_table('client_platform_credentials')
    op.drop_index(op.f('ix_categories_id'), table_name='categories')
    op.drop_table('categories')
    op.drop_index(op.f('ix_category_templates_id'), table_name='category_templates')
    op.drop_table('category_templates')
    # ### end Alembic commands ###
