"""add gorgias credentials table

Revision ID: dc485805db8a
Revises: c5c282940950
Create Date: 2026-04-24 08:35:20.764343

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dc485805db8a'
down_revision: Union[str, Sequence[str], None] = 'c5c282940950'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client_gorgias_credentials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('api_key_encrypted', sa.String(), nullable=False),
    sa.Column('api_base_url', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_id')
    )
    op.create_index(op.f('ix_client_gorgias_credentials_id'), 'client_gorgias_credentials', ['id'], unique=False)
    op.drop_index(op.f('ix_client_platform_credentials_id'), table_name='client_platform_credentials')
    op.drop_table('client_platform_credentials')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client_platform_credentials',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('client_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('credential_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('api_key_encrypted', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('api_base_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], name=op.f('client_platform_credentials_client_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('client_platform_credentials_pkey'))
    )
    op.create_index(op.f('ix_client_platform_credentials_id'), 'client_platform_credentials', ['id'], unique=False)
    op.drop_index(op.f('ix_client_gorgias_credentials_id'), table_name='client_gorgias_credentials')
    op.drop_table('client_gorgias_credentials')
    # ### end Alembic commands ###
